### ISSUE TITLE
Obtain feedback on SQLite database for file discovery

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/data#1]
A sample database is available for for plot-level RGB data for 2018-05-08 (May, 08, 2018) on [Google Drive](https://drive.google.com/open?id=1VyPtQYcj5xaaB7OUB6UILNd9It3tfgeD).

This database provides a view named `unified` which contains searchable cultivar, weather, plot, and genetic fields.

**Comment by dlebauer** [comment]
This would be nice to have as an index with the current or perhaps a future data publication ... currently the file manifest is a bunch of json files w/o much metadata, e.g.


```
{
    "collections": {
        "RGB GeoTIFFs (Masked) - 2017-07-30": {
            "datasets": {
                "RGB GeoTIFFs (Masked) - 2017-07-30__14-40-12-835": {
                    "files": [
                        {
                            "path": "season-4/sites/ua-mac/Level_2/rgb_mask/2017-07-30/2017-07-30__14-40-12-835/rgb_mask_L1_ua-mac_2017-07-30__14-40-12-835_left_mask.tif", 
                            "checksum": "795885d4cafe612e9dbcedc860b95166", 
                            "name": "rgb_mask_L1_ua-mac_2017-07-30__14-40-12-835_left_mask.tif", 
                            "size": 8653435
                        }
                    ]
                }, 
                "RGB GeoTIFFs (Masked) - 2017-07-30__14-59-05-402": {
                    "files": [
                        {
                            "path": "season-4/sites/ua-mac/Level_2/rgb_mask/2017-07-30/2017-07-30__14-59-05-402/rgb_mask_L1_ua-mac_2017-07-30__14-59-05-402_left_mask.tif", 
                            "checksum": "def2036e58ea3fd647fd78c998a29219", 
                            "name": "rgb_mask_L1_ua-mac_2017-07-30__14-59-05-402_left_mask.tif", 
                            "size": 19730184
                        }
                    ]
                }, 
```

**Comment by Chris-Schnaufer** [comment]
Lets meet and discuss next steps

**Comment by dlebauer** [comment]
@Chris-Schnaufer I've reviewed this - a few things to change:

* all climate variables should be trimmed to 4 significant digits 123.4 or 0.01234) 
* remove gene_markers table
* presumably this is only on a subset? I only see RGB
* if you need access to the actual filesystem to run your scripts (rather than downloading files) you can use workbench.terraref.org

I will write this out more clearly in https://github.com/terraref/data-paper/issues/20
